name: Deploy Kartoshka Bot

# Триггеры: ручной и по пушу в main (можно оставить только workflow_dispatch)
on:
  workflow_dispatch:     # ручной запуск из UI
  push:
    branches: [ main ]   # (если нужно по-прежнему автоматом)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=yes \
            ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            set -e
            cd ~/projects/kartoshka_bot
            git pull origin main

            cat > .env << EOT
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            EDITOR_IDS=${{ secrets.EDITOR_IDS }}
            PUBLISH_CHAT_ID=${{ secrets.PUBLISH_CHAT_ID }}
            BOT_NAME="${{ secrets.BOT_NAME }}"
            POST_FREQUENCY_MINUTES=${{ secrets.POST_FREQUENCY_MINUTES }}
            CRYPTOSELECTARCHY=${{ secrets.CRYPTOSELECTARCHY }}
            VOTES_TO_APPROVE=${{ secrets.VOTES_TO_APPROVE }}
            VOTES_TO_REJECT=${{ secrets.VOTES_TO_REJECT }}
            EOT

            sudo systemctl restart kartoshka_bot.service

            if ! sudo systemctl is-active --quiet kartoshka_bot.service; then
              echo "✖ Service failed to start" >&2
              sudo journalctl -u kartoshka_bot.service --no-pager -n 50 >&2
              exit 1
            fi

            echo "✔ Service is running."
          EOF
