name: Deploy Kartoshka Bot

on:
  workflow_dispatch:    # ручной запуск из GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -q -o StrictHostKeyChecking=yes ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          set -e

          # Отключаем MOTD
          touch ~/.hushlogin || true

          cd ~/projects/kartoshka_bot
          git pull origin main

          # Перезаписываем .env — маркер 'EOT' без отступов
          cat > .env << 'EOT'
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          EDITOR_IDS=${{ secrets.EDITOR_IDS }}
          PUBLISH_CHAT_ID=${{ secrets.PUBLISH_CHAT_ID }}
          BOT_NAME="${{ secrets.BOT_NAME }}"
          POST_FREQUENCY_MINUTES=${{ secrets.POST_FREQUENCY_MINUTES }}
          CRYPTOSELECTARCHY=${{ secrets.CRYPTOSELECTARCHY }}
          VOTES_TO_APPROVE=${{ secrets.VOTES_TO_APPROVE }}
          VOTES_TO_REJECT=${{ secrets.VOTES_TO_REJECT }}
          EOT

          sudo systemctl restart kartoshka_bot.service

          if ! sudo systemctl is-active --quiet kartoshka_bot.service; then
            echo "✖ kartoshka_bot.service failed to start!" >&2
            sudo journalctl -u kartoshka_bot.service --no-pager -n 50 >&2
            exit 1
          fi

          echo "✔ kartoshka_bot.service is running."
          EOF
