name: CI & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# нужно для пуша бейджа и комментариев в PR
permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем код
    - uses: actions/checkout@v4

    # 2. Ставим Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-asyncio pytest-cov

    # 4. Переменные окружения, которые нужны тестам
    - name: Prepare runtime env vars
      run: |
        echo "BOT_TOKEN=123456789:TEST_TOKEN_FOR_TESTING" >> $GITHUB_ENV
        echo "EDITOR_IDS=123,456,789" >> $GITHUB_ENV
        echo "PUBLISH_CHAT_ID=-1001234567890" >> $GITHUB_ENV
        echo "BOT_NAME=TestBot" >> $GITHUB_ENV
        echo "POST_FREQUENCY_MINUTES=60" >> $GITHUB_ENV
        echo "CRYPTOSELECTARCHY=true" >> $GITHUB_ENV
        echo "VOTES_TO_APPROVE=3" >> $GITHUB_ENV
        echo "VOTES_TO_REJECT=3" >> $GITHUB_ENV

    # 5. Запуск всех тестов с покрытием
    - name: Run tests with coverage
      run: |
        pytest -v \
          --cov=kartoshka_bot \
          --cov-report=term-missing:skip-covered \
          --cov-report=xml \
          --cov-report=html

    # 6. Загружаем HTML‑отчёт как artefact
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html
        path: htmlcov/

    # 7. Создаём/обновляем coverage.svg
    - name: Create coverage.svg badge
      id: badge
      uses: tj-actions/coverage-badge-py@v2       # живой экшен
      with:
        output: coverage.svg

    # 8. Проверяем, изменился ли бейдж
    - name: Verify badge changed
      id: verify
      uses: tj-actions/verify-changed-files@v16
      with:
        files: coverage.svg

    # 9. Коммитим и пушим в main, только если файл обновился
    - name: Commit and push badge
      if: steps.verify.outputs.files_changed == 'true' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name  "github-actions[bot]"
        git add coverage.svg
        git commit -m "chore: update coverage badge"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 10. Вычисляем процент покрытия для комментария
    - name: Extract coverage %
      id: cov
      run: |
        python - <<'PY'
        import xml.etree.ElementTree as ET, math, os
        pct = math.floor(float(ET.parse('coverage.xml').getroot().attrib['line-rate'])*100)
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            fh.write(f"pct={pct}\n")
        PY

    # 11. Комментарий в PR (sticky — обновляет, а не плодит)
    - name: PR comment with coverage
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          🧪 **Test coverage:** **${{ steps.cov.outputs.pct }}%**
